# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adastra < Formula
  desc "Your App Store growth stack in one binary — ASO + Apple Ads CLI"
  homepage "https://github.com/tawhidkuet04/adastra"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tawhidkuet04/adastra/releases/download/v0.1.0/adastra_0.1.0_darwin_amd64.tar.gz"
      sha256 "ba114bae6d4798a52ecfddd42fdf191a2735ad4ad5a421d3b31c1014c2f3cd4a"

      define_method(:install) do
        bin.install "adastra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tawhidkuet04/adastra/releases/download/v0.1.0/adastra_0.1.0_darwin_arm64.tar.gz"
      sha256 "4ba15dcb8e6c23cc3577fed3a00818f0248062499471c096cb935b53479849c9"

      define_method(:install) do
        bin.install "adastra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/adastra/releases/download/v0.1.0/adastra_0.1.0_linux_amd64.tar.gz"
      sha256 "14abd05b72c003a4fa2a007847fadb434c64548a05cc72ceb430d338e888b254"
      define_method(:install) do
        bin.install "adastra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/adastra/releases/download/v0.1.0/adastra_0.1.0_linux_arm64.tar.gz"
      sha256 "6283fd33440bf546ba8887fd0cf65d6eb3b591b3cdc970e122cf2884c894386c"
      define_method(:install) do
        bin.install "adastra"
      end
    end
  end

  test do
    system "#{bin}/adastra --version"
  end
end
