# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appadscli < Formula
  desc "Your App Store growth stack in one binary — ASO + Apple Ads CLI"
  homepage "https://github.com/tawhidkuet04/appadscli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tawhidkuet04/appadscli/releases/download/v0.3.0/appadscli_0.3.0_darwin_amd64.tar.gz"
      sha256 "03a1a784a28f8d02001df95364f33c6f0ae5a1d768ac11d7e63e5b5f76a47bc6"

      define_method(:install) do
        bin.install "appadscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tawhidkuet04/appadscli/releases/download/v0.3.0/appadscli_0.3.0_darwin_arm64.tar.gz"
      sha256 "284bef9cf630db96bcbe2606b1f378aea14e15dc9a9b77720133a3fa0b5b7a11"

      define_method(:install) do
        bin.install "appadscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/appadscli/releases/download/v0.3.0/appadscli_0.3.0_linux_amd64.tar.gz"
      sha256 "2ecea64a5d8b76ac862d7b640ad8f3f4cd1e6500474c5130d6d5960f8d157f78"
      define_method(:install) do
        bin.install "appadscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/appadscli/releases/download/v0.3.0/appadscli_0.3.0_linux_arm64.tar.gz"
      sha256 "785def50ef5b4b81ddc6185d7ff465e90db6af317feaa5cbd68ac2000e8f655e"
      define_method(:install) do
        bin.install "appadscli"
      end
    end
  end

  test do
    system "#{bin}/appadscli --version"
  end
end
