# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appadscli < Formula
  desc "Your App Store growth stack in one binary — ASO + Apple Ads CLI"
  homepage "https://github.com/appadscli/appadscli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appadscli/appadscli/releases/download/v0.3.1/appadscli_0.3.1_darwin_amd64.tar.gz"
      sha256 "108d6fb455fdc969d5c0e103e3351be4f699f45ed3e47a2c69a19f01261158cd"

      define_method(:install) do
        bin.install "appadscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appadscli/appadscli/releases/download/v0.3.1/appadscli_0.3.1_darwin_arm64.tar.gz"
      sha256 "dd057b471f3137d0740366abb16a0d8395cfaa1e06e4d7e8be9b04f26ee660c4"

      define_method(:install) do
        bin.install "appadscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appadscli/appadscli/releases/download/v0.3.1/appadscli_0.3.1_linux_amd64.tar.gz"
      sha256 "4b729e40e44d79fa67cf7451d30eb9f67aa5d0b40d59900ca456a22a155b36ec"
      define_method(:install) do
        bin.install "appadscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appadscli/appadscli/releases/download/v0.3.1/appadscli_0.3.1_linux_arm64.tar.gz"
      sha256 "12d384cb6270fde6bd10ef74a420d2c3787e53d63fa4e4343400e3c0f1ca94fb"
      define_method(:install) do
        bin.install "appadscli"
      end
    end
  end

  test do
    system "#{bin}/appadscli --version"
  end
end
