# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asacli < Formula
  desc "Your App Store growth stack in one binary — ASO + Apple Ads CLI"
  homepage "https://github.com/tawhidkuet04/asacli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tawhidkuet04/asacli/releases/download/v0.2.0/asacli_0.2.0_darwin_amd64.tar.gz"
      sha256 "40b4b3099c423f30f553c0013a9e34b175c5604ea775b9350b0029a5b397a369"

      define_method(:install) do
        bin.install "asacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tawhidkuet04/asacli/releases/download/v0.2.0/asacli_0.2.0_darwin_arm64.tar.gz"
      sha256 "7098e396f5beb8a46f34cb1cb02bf183fa0349db964890bbeaea49187b1da65b"

      define_method(:install) do
        bin.install "asacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/asacli/releases/download/v0.2.0/asacli_0.2.0_linux_amd64.tar.gz"
      sha256 "89ece136842c32727a5df30c59298726e31abf7689836a3ea3464df168f4db70"
      define_method(:install) do
        bin.install "asacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tawhidkuet04/asacli/releases/download/v0.2.0/asacli_0.2.0_linux_arm64.tar.gz"
      sha256 "8d009fd61c621688709cd9dc296a9e916fb353ce920fb8c8d3ee5daeff1bd9c8"
      define_method(:install) do
        bin.install "asacli"
      end
    end
  end

  test do
    system "#{bin}/asacli --version"
  end
end
